version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=medical_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/medical_db
      - DJANGO_SECRET_KEY=tusupersecretkey
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: